# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STW9ORDtgqmnxhVaBQZHD0FepW2muriy
"""

import sqlite3

def init_agv_group_system():
    conn = sqlite3.connect('agv_treasury.db')
    cursor = conn.cursor()

    # 1. Create the Subsidiaries Table (The Risk Profiles)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Subsidiaries (
        SubID INTEGER PRIMARY KEY,
        Name TEXT,
        Sector TEXT,
        HedgeThreshold REAL  -- The % change that triggers a move
    )
    ''')

    # 2. Create the Treasury Table (The Cash)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Treasury (
        SubID INTEGER PRIMARY KEY,
        NGN_Balance REAL,
        USD_Balance REAL,
        FOREIGN KEY (SubID) REFERENCES Subsidiaries(SubID)
    )
    ''')

    # 3. Populate AGV Group Units
    subs = [
        (1, 'AGV Media & News Hub', 'Journalism/Media', 1.0), # Sensitive
        (2, 'AGV Systems Engineering', 'IT/Infrastructure', 2.5), # Moderate
        (3, 'AGV Heritage Logistics', 'Supply Chain/Bakery', 5.0) # Conservative
    ]

    # 4. Initial Cash Balances (Starting with 10M NGN each)
    cash = [
        (1, 10000000.00, 0.00),
        (2, 10000000.00, 0.00),
        (3, 10000000.00, 0.00)
    ]

    cursor.executemany("INSERT OR REPLACE INTO Subsidiaries VALUES (?,?,?,?)", subs)
    cursor.executemany("INSERT OR REPLACE INTO Treasury VALUES (?,?,?)", cash)

    conn.commit()
    conn.close()
    print("🏢 AGV Group Infrastructure: ONLINE.")

init_agv_group_system()

import sqlite3

def init_tiered_agv_system():
    conn = sqlite3.connect('agv_treasury.db')
    cursor = conn.cursor()

    # Define the tiered balances
    # (SubID, NGN_Balance, USD_Balance)
    tiered_cash = [
        (1, 45000000.00, 0.00), # Media Hub - Large Scale
        (2, 15000000.00, 0.00), # Engineering - Mid Scale
        (3, 5000000.00, 0.00)   # Logistics - Lean Scale
    ]

    # Update the Treasury with these new numbers
    cursor.executemany("INSERT OR REPLACE INTO Treasury (SubID, NGN_Balance, USD_Balance) VALUES (?,?,?)", tiered_cash)

    conn.commit()
    conn.close()
    print("📈 AGV Group Treasury: Tiered Capital Allocation Complete.")

init_tiered_agv_system()

import sqlite3
import random

def run_agv_automated_treasury(simulated_rate_change):
    conn = sqlite3.connect('agv_treasury.db')
    cursor = conn.cursor()

    # 1. Fetch our Subsidiaries and their Balances
    cursor.execute('''
        SELECT s.SubID, s.Name, s.HedgeThreshold, t.NGN_Balance, t.USD_Balance
        FROM Subsidiaries s
        JOIN Treasury t ON s.SubID = t.SubID
    ''')
    units = cursor.fetchall()

    print(f"📈 Market Update: USD/NGN moved {simulated_rate_change}%")
    print("-" * 50)

    for unit in units:
        sub_id, name, threshold, ngn_bal, usd_bal = unit

        # 2. DECISION LOGIC
        if abs(simulated_rate_change) >= threshold:
            # EXECUTION: Hedge 15% of current NGN to USD
            hedge_amount_ngn = ngn_bal * 0.15
            new_ngn = ngn_bal - hedge_amount_ngn

            # Simple conversion (assuming 1 USD = 1500 NGN for the simulation)
            added_usd = hedge_amount_ngn / 1500
            new_usd = usd_bal + added_usd

            # 3. UPDATE DATABASE (The 'Trade')
            cursor.execute("UPDATE Treasury SET NGN_Balance = ?, USD_Balance = ? WHERE SubID = ?",
                           (new_ngn, new_usd, sub_id))

            print(f"🚨 ALERT [{name}]: Threshold {threshold}% breached! Hedged ₦{hedge_amount_ngn:,.2f}")
        else:
            print(f"✅ [{name}]: Volatility ({simulated_rate_change}%) within safe limit ({threshold}%).")

    conn.commit()
    conn.close()

# --- TEST THE SYSTEM ---
# Let's simulate a 'Market Shock' of 3.5%
run_agv_automated_treasury(3.5)

import sqlite3
import pandas as pd

def run_unified_agv_system(market_move):
    # 1. Connect and Ensure Tables Exist (Self-Healing)
    conn = sqlite3.connect('agv_treasury_master.db')
    cursor = conn.cursor()

    cursor.execute('CREATE TABLE IF NOT EXISTS Subsidiaries (SubID INTEGER PRIMARY KEY, Name TEXT, HedgeThreshold REAL)')
    cursor.execute('CREATE TABLE IF NOT EXISTS Treasury (SubID INTEGER PRIMARY KEY, NGN_Balance REAL, USD_Balance REAL)')

    # 2. Reset / Populate with our Tiered Balances (If empty)
    cursor.execute("SELECT COUNT(*) FROM Subsidiaries")
    if cursor.fetchone()[0] == 0:
        subs = [(1, 'AGV Media & News Hub', 1.0), (2, 'AGV Systems Engineering', 2.5), (3, 'AGV Heritage Logistics', 5.0)]
        cash = [(1, 45000000.0, 0.0), (2, 15000000.0, 0.0), (3, 5000000.0, 0.0)]
        cursor.executemany("INSERT INTO Subsidiaries VALUES (?,?,?)", subs)
        cursor.executemany("INSERT INTO Treasury VALUES (?,?,?)", cash)
        conn.commit()

    # 3. RUN THE AUDIT LOGIC
    cursor.execute('''
        SELECT s.SubID, s.Name, s.HedgeThreshold, t.NGN_Balance, t.USD_Balance
        FROM Subsidiaries s
        JOIN Treasury t ON s.SubID = t.SubID
    ''')
    units = cursor.fetchall()

    print(f"🌍 AGV GROUP MARKET REPORT | USD/NGN CHANGE: {market_move}%")
    print("="*60)

    for unit in units:
        sub_id, name, threshold, ngn_bal, usd_bal = unit

        if abs(market_move) >= threshold:
            # HEDGE: Move 15% of NGN to USD
            amount_to_hedge = ngn_bal * 0.15
            new_ngn = ngn_bal - amount_to_hedge
            new_usd = usd_bal + (amount_to_hedge / 1500) # Mock Rate 1500

            cursor.execute("UPDATE Treasury SET NGN_Balance = ?, USD_Balance = ? WHERE SubID = ?", (new_ngn, new_usd, sub_id))
            print(f"🚨 HEDGE EXECUTED: {name.ljust(25)} | Moved ₦{amount_to_hedge:,.2f} to USD")
        else:
            print(f"✅ STABLE:         {name.ljust(25)} | Risk within {threshold}% limit")

    conn.commit()

    # 4. SHOW FINAL CONSOLIDATED BALANCE SHEET
    print("\n" + "="*60)
    print("AGV GROUP CONSOLIDATED BALANCE SHEET (POST-MARKET MOVE)")
    df = pd.read_sql_query("SELECT s.Name, t.NGN_Balance, t.USD_Balance FROM Subsidiaries s JOIN Treasury t ON s.SubID = t.SubID", conn)
    conn.close()
    return df

# --- SIMULATE A 3.0% MARKET DROP ---
run_unified_agv_system(3.0)

import sqlite3
from datetime import datetime

def log_transaction(sub_name, amount_ngn, rate):
    conn = sqlite3.connect('agv_treasury_master.db')
    cursor = conn.cursor()

    # Create the log table if it doesn't exist
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS Hedge_Logs (
            LogID INTEGER PRIMARY KEY,
            Timestamp TEXT,
            Subsidiary TEXT,
            Amount_NGN REAL,
            Execution_Rate REAL
        )
    ''')

    # Record the entry
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cursor.execute("INSERT INTO Hedge_Logs (Timestamp, Subsidiary, Amount_NGN, Execution_Rate) VALUES (?,?,?,?)",
                   (timestamp, sub_name, amount_ngn, rate))

    conn.commit()
    conn.close()

print("✅ Audit Logging System Integrated.")

import requests
import sqlite3
import pandas as pd

def test_live_agv_hedge():
    # 1. GET REAL WORLD DATA (No Key Required for this endpoint)
    url = "https://open.er-api.com/v6/latest/USD"

    try:
        response = requests.get(url)
        data = response.json()
        live_rate = data['rates']['NGN']
        print(f"📡 LIVE DATA FETCHED: 1 USD = ₦{live_rate:,.2f}")
    except Exception as e:
        print(f"❌ API Failure: {e}")
        return

    # 2. CALCULATE MARKET MOVE
    # Let's assume the business day started at ₦1,450.00
    opening_rate = 1450.00
    market_move = ((live_rate - opening_rate) / opening_rate) * 100

    print(f"📉 Calculated Market Volatility: {market_move:.2f}%")
    print("="*60)

    # 3. EXECUTE THE TREASURY LOGIC (Unified System)
    # This calls the hardened function we built in the previous step
    # Make sure you've run the 'run_unified_agv_system' cell first!
    final_balances = run_unified_agv_system(market_move)

    return final_balances

# --- EXECUTE THE LIVE TEST ---
test_live_agv_hedge()

import plotly.express as px
import pandas as pd
import sqlite3

def visualize_treasury_impact():
    conn = sqlite3.connect('agv_treasury_master.db')

    # Fetch the final results
    df = pd.read_sql_query("""
        SELECT s.Name, t.NGN_Balance, t.USD_Balance
        FROM Subsidiaries s
        JOIN Treasury t ON s.SubID = t.SubID
    """, conn)
    conn.close()

    # Create an interactive bar chart for USD Balances
    fig = px.bar(df, x='Name', y='USD_Balance',
                 title='AGV Group: Automated USD Acquisitions (Live Market Trigger)',
                 labels={'USD_Balance':'USD Balance ($)', 'Name':'Subsidiary'},
                 color='USD_Balance',
                 color_continuous_scale='Greens')

    fig.update_layout(template='plotly_dark', plot_bgcolor='rgba(0,0,0,0)')
    fig.show()

visualize_treasury_impact()

conn = sqlite3.connect('agv_treasury_master.db')
logs_df = pd.read_sql_query("SELECT * FROM Hedge_Logs", conn)
conn.close()

print("📋 OFFICIAL AGV GROUP AUDIT LOG")
print("="*60)
print(logs_df)

import sqlite3
import pandas as pd
from datetime import datetime

def run_agv_production_engine(market_move):
    conn = sqlite3.connect('agv_treasury_final.db')
    cursor = conn.cursor()

    # 1. ARCHITECTURE SETUP (Ensure all 3 tables exist)
    cursor.execute('CREATE TABLE IF NOT EXISTS Subsidiaries (SubID INTEGER PRIMARY KEY, Name TEXT, HedgeThreshold REAL)')
    cursor.execute('CREATE TABLE IF NOT EXISTS Treasury (SubID INTEGER PRIMARY KEY, NGN_Balance REAL, USD_Balance REAL)')
    cursor.execute('''CREATE TABLE IF NOT EXISTS Hedge_Logs (
                        LogID INTEGER PRIMARY KEY, Timestamp TEXT, Subsidiary TEXT,
                        Action TEXT, Amount_NGN REAL, Rate REAL)''')

    # 2. INITIAL SEEDING (If empty)
    cursor.execute("SELECT COUNT(*) FROM Subsidiaries")
    if cursor.fetchone()[0] == 0:
        subs = [(1, 'AGV Media & News Hub', 1.0), (2, 'AGV Systems Engineering', 2.5), (3, 'AGV Heritage Logistics', 5.0)]
        cash = [(1, 45000000.0, 0.0), (2, 15000000.0, 0.0), (3, 5000000.0, 0.0)]
        cursor.executemany("INSERT INTO Subsidiaries VALUES (?,?,?)", subs)
        cursor.executemany("INSERT INTO Treasury VALUES (?,?,?)", cash)
        conn.commit()

    # 3. EXECUTION LOGIC
    cursor.execute("SELECT s.SubID, s.Name, s.HedgeThreshold, t.NGN_Balance, t.USD_Balance FROM Subsidiaries s JOIN Treasury t ON s.SubID = t.SubID")
    units = cursor.fetchall()

    print(f"📡 AGV GROUP COMMAND | MARKET VOLATILITY: {market_move:.2f}%")

    for unit in units:
        sub_id, name, threshold, ngn_bal, usd_bal = unit
        if abs(market_move) >= threshold:
            # HEDGE ACTION
            hedge_ngn = ngn_bal * 0.15
            new_ngn = ngn_bal - hedge_ngn
            new_usd = usd_bal + (hedge_ngn / 1500)

            # Update Balances
            cursor.execute("UPDATE Treasury SET NGN_Balance = ?, USD_Balance = ? WHERE SubID = ?", (new_ngn, new_usd, sub_id))

            # WRITE TO AUDIT LOG (The fix for your error)
            now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            cursor.execute("INSERT INTO Hedge_Logs (Timestamp, Subsidiary, Action, Amount_NGN, Rate) VALUES (?,?,?,?,?)",
                           (now, name, 'AUTO-HEDGE', hedge_ngn, 1500))

            print(f"🚨 ALERT: {name} threshold breached. Audit log updated.")

    conn.commit()

    # 4. SHOW RESULTS
    print("\n--- CONSOLIDATED AUDIT LOG ---")
    logs = pd.read_sql_query("SELECT * FROM Hedge_Logs", conn)
    conn.close()
    return logs

# --- TEST IT ---
run_agv_production_engine(6.1)

import requests
import sqlite3
import pandas as pd
import plotly.express as px
from datetime import datetime

def run_agv_live_production_system():
    # --- 1. THE PING (Live API Call) ---
    url = "https://open.er-api.com/v6/latest/USD"
    try:
        response = requests.get(url)
        data = response.json()
        live_rate = data['rates']['NGN']
        opening_rate = 1450.00  # Our baseline
        market_move = ((live_rate - opening_rate) / opening_rate) * 100
        print(f"📡 PING SUCCESSFUL | Live Rate: ₦{live_rate:,.2f} | Move: {market_move:.2f}%")
    except Exception as e:
        print(f"❌ PING FAILED: {e}")
        return

    # --- 2. DATABASE ARCHITECTURE ---
    conn = sqlite3.connect('agv_production.db')
    cursor = conn.cursor()

    cursor.execute('CREATE TABLE IF NOT EXISTS Subsidiaries (SubID INTEGER PRIMARY KEY, Name TEXT, HedgeThreshold REAL)')
    cursor.execute('CREATE TABLE IF NOT EXISTS Treasury (SubID INTEGER PRIMARY KEY, NGN_Balance REAL, USD_Balance REAL)')
    cursor.execute('CREATE TABLE IF NOT EXISTS Hedge_Logs (LogID INTEGER PRIMARY KEY, Timestamp TEXT, Subsidiary TEXT, Amount_NGN REAL)')

    # Seed data if database is new
    cursor.execute("SELECT COUNT(*) FROM Subsidiaries")
    if cursor.fetchone()[0] == 0:
        cursor.executemany("INSERT INTO Subsidiaries VALUES (?,?,?)",
                           [(1, 'Media Hub', 1.0), (2, 'Systems Engineering', 2.5), (3, 'Heritage Logistics', 5.0)])
        cursor.executemany("INSERT INTO Treasury VALUES (?,?,?)",
                           [(1, 45000000.0, 0.0), (2, 15000000.0, 0.0), (3, 5000000.0, 0.0)])
        conn.commit()

    # --- 3. EXECUTION LOGIC ---
    cursor.execute("SELECT s.SubID, s.Name, s.HedgeThreshold, t.NGN_Balance, t.USD_Balance FROM Subsidiaries s JOIN Treasury t ON s.SubID = t.SubID")
    units = cursor.fetchall()

    for unit in units:
        sub_id, name, threshold, ngn_bal, usd_bal = unit
        if abs(market_move) >= threshold:
            hedge_ngn = ngn_bal * 0.15
            new_ngn = ngn_bal - hedge_ngn
            new_usd = usd_bal + (hedge_ngn / live_rate) # Using real-time rate for conversion

            cursor.execute("UPDATE Treasury SET NGN_Balance = ?, USD_Balance = ? WHERE SubID = ?", (new_ngn, new_usd, sub_id))
            cursor.execute("INSERT INTO Hedge_Logs (Timestamp, Subsidiary, Amount_NGN) VALUES (?,?,?)",
                           (datetime.now().strftime("%Y-%m-%d %H:%M:%S"), name, hedge_ngn))

    conn.commit()

    # --- 4. THE CORRECTED VISUALIZATION ---
    df = pd.read_sql_query("SELECT s.Name, t.NGN_Balance, t.USD_Balance FROM Subsidiaries s JOIN Treasury t ON s.SubID = t.SubID", conn)
    conn.close()

    fig = px.bar(df,
                 x='Name',
                 y='USD_Balance',
                 title='AGV Group: Live USD Assets Post-Hedge',
                 labels={'Name': 'Business Subsidiary', 'USD_Balance': 'Total USD Holdings ($)'}, # Fixed Axis
                 color='USD_Balance',
                 color_continuous_scale='Viridis')

    fig.update_layout(template='plotly_dark')
    fig.show()

    return df

# Execute the full production cycle
run_agv_live_production_system()