# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AkGr1EdoYUGlMA_dSq5Wx8kbjJxOkd4J
"""

import sqlite3
import pandas as pd
from datetime import datetime

def init_hospital_power_system():
    conn = sqlite3.connect('hospital_power_hub.db')
    cursor = conn.cursor()

    # 1. Create Zone Table (Hospital Layout)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Hospital_Zones (
        ZoneID INTEGER PRIMARY KEY,
        ZoneName TEXT,
        RequiredVoltage REAL, -- Usually 230V
        Criticality TEXT       -- Life-Support, Imaging, or General
    )
    ''')

    # 2. Create Sensor Log (The Heartbeat)
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Power_Sensors (
        ReadingID INTEGER PRIMARY KEY,
        Timestamp TEXT,
        ZoneID INTEGER,
        Voltage REAL,
        Temperature REAL,
        Status TEXT
    )
    ''')

    # 3. Populate Hospital Zones
    zones = [
        (1, 'ICU & Operating Theaters', 230.0, 'LIFE-SUPPORT'),
        (2, 'MRI & Radiology Wing', 230.0, 'DIAGNOSTIC'),
        (3, 'Admin & General Services', 230.0, 'NON-ESSENTIAL')
    ]
    cursor.executemany("INSERT OR REPLACE INTO Hospital_Zones VALUES (?,?,?,?)", zones)

    conn.commit()
    conn.close()
    print("🏥 St. Jude's Medical Power Hub: ARCHITECTURE INITIALIZED.")

init_hospital_power_system()

import sqlite3

def upgrade_to_hybrid_system():
    conn = sqlite3.connect('hospital_power_hub.db')
    cursor = conn.cursor()

    # 1. Create Source Health Table
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS Power_Sources (
        SourceID INTEGER PRIMARY KEY,
        SourceName TEXT,
        CurrentVoltage REAL,
        Fuel_or_Charge REAL, -- Fuel Level for Gen / Battery for Solar
        Is_Active INTEGER     -- 1 for On, 0 for Off
    )
    ''')

    # 2. Initial Source Setup
    sources = [
        (1, 'Public Grid', 230.0, 100.0, 1), # Starting with Grid Active
        (2, 'Solar/Battery Bank', 230.0, 85.0, 0),
        (3, 'Emergency Diesel Gen', 0.0, 100.0, 0)
    ]
    cursor.executemany("INSERT OR REPLACE INTO Power_Sources VALUES (?,?,?,?,?)", sources)

    conn.commit()
    conn.close()
    print("🔋 Hybrid Power Sources (Grid/Solar/Gen) Online.")

upgrade_to_hybrid_system()

import time

def simulate_grid_collapse():
    conn = sqlite3.connect('hospital_power_hub.db')
    cursor = conn.cursor()

    print("📉 [14:00] MONITORING: Grid voltage starting to sag...")

    # Simulate a Grid failure (dropping to 160V)
    grid_fail_voltage = 160.0

    # 1. AUTOMATIC EMERGENCY RESPONSE
    print("🚨 [14:01] ALERT: Grid Critical (160V). Executing ICU Protection...")

    # Step A: Engage Solar/Battery for ICU (Zone 1)
    cursor.execute("UPDATE Power_Sources SET Is_Active = 1 WHERE SourceName = 'Solar/Battery Bank'")

    # Step B: Shed Non-Essential Load (Zone 3) to save battery
    cursor.execute("UPDATE Power_Sensors SET Status = 'SHEDDED' WHERE ZoneID = 3")
    print("⚡ [14:01] ACTION: Admin Wing (Zone 3) Disconnected.")

    # Step C: Crank the Generator
    print("⚙️ [14:02] ACTION: Emergency Diesel Generator Cranking...")
    time.sleep(2) # Simulating the 10-second physical delay
    cursor.execute("UPDATE Power_Sources SET CurrentVoltage = 230.0, Is_Active = 1 WHERE SourceName = 'Emergency Diesel Gen'")

    # Step D: Confirm ICU Safety
    print("✅ [14:03] STATUS: ICU stabilized on Solar + Gen. Grid isolated.")

    conn.commit()

    # Check the final status of our sources
    results = pd.read_sql_query("SELECT SourceName, CurrentVoltage, Is_Active FROM Power_Sources", conn)
    conn.close()
    return results

simulate_grid_collapse()

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sqlite3
import pandas as pd

def render_hospital_dashboard():
    conn = sqlite3.connect('hospital_power_hub.db')

    # 1. Fetch Source Data
    df_sources = pd.read_sql_query("SELECT SourceName, CurrentVoltage, Is_Active FROM Power_Sources", conn)
    # 2. Fetch Zone Data
    df_zones = pd.read_sql_query("SELECT ZoneName, Criticality FROM Hospital_Zones", conn)
    conn.close()

    # --- Create Dashboard ---
    fig = make_subplots(
        rows=1, cols=2,
        specs=[[{"type": "pie"}, {"type": "bar"}]],
        subplot_titles=("Current Power Mix (Source)", "Zone Criticality Distribution")
    )

    # Left Chart: Active Sources
    active_sources = df_sources[df_sources['Is_Active'] == 1]
    fig.add_trace(
        go.Pie(labels=active_sources['SourceName'],
               values=[1]*len(active_sources), # Equal weight for active sources in this view
               hole=.4,
               marker=dict(colors=['#00CC96', '#636EFA', '#EF553B'])),
        row=1, col=1
    )

    # Right Chart: Zone Overview
    fig.add_trace(
        go.Bar(x=df_zones['ZoneName'],
               y=[230, 230, 0], # Visualizing the "Shedding" of Admin (0V)
               name="Live Voltage (V)",
               marker_color=['#FF4B4B', '#FACC15', '#4B4B4B']),
        row=1, col=2
    )

    fig.update_layout(
        title_text="🏥 St. Jude's Medical Center: Live Infrastructure Health",
        template="plotly_dark",
        showlegend=True
    )

    fig.show()

render_hospital_dashboard()

import plotly.graph_objects as go
from plotly.subplots import make_subplots
import sqlite3
import pandas as pd

def render_modern_hospital_dash():
    conn = sqlite3.connect('hospital_power_hub.db')

    # Simulate realistic Load Data (Real-time power draw in kW)
    # ICU: 150kW | Imaging: 100kW | Admin: 20kW (Shedded/Low)
    loads = {'ICU': 150, 'Imaging': 100, 'Admin': 0}

    # 1. Fetch Source Stats
    df_sources = pd.read_sql_query("SELECT * FROM Power_Sources", conn)
    conn.close()

    # Create the modern layout
    fig = make_subplots(
        rows=2, cols=3,
        specs=[[{"type": "indicator"}, {"type": "indicator"}, {"type": "indicator"}],
               [{"type": "bar", "colspan": 3}, None, None]],
        vertical_spacing=0.15,
        subplot_titles=("Grid Health", "Solar Yield", "Generator Status", "Live Load Distribution by Zone (kW)")
    )

    # --- TOP ROW: INDICATOR GAUGES ---
    # Grid Gauge
    fig.add_trace(go.Indicator(
        mode = "gauge+number", value = df_sources.loc[0, 'CurrentVoltage'],
        title = {'text': "Grid (V)"},
        gauge = {'axis': {'range': [0, 250]}, 'bar': {'color': "#636EFA"}}
    ), row=1, col=1)

    # Solar Gauge
    fig.add_trace(go.Indicator(
        mode = "gauge+number", value = df_sources.loc[1, 'Fuel_or_Charge'],
        title = {'text': "Solar Battery %"},
        gauge = {'axis': {'range': [0, 100]}, 'bar': {'color': "#00CC96"}}
    ), row=1, col=2)

    # Gen Gauge
    fig.add_trace(go.Indicator(
        mode = "gauge+number", value = df_sources.loc[2, 'Fuel_or_Charge'],
        title = {'text': "Gen Fuel %"},
        gauge = {'axis': {'range': [0, 100]}, 'bar': {'color': "#EF553B"}}
    ), row=1, col=3)

    # --- BOTTOM ROW: POWER LOAD BAR ---
    fig.add_trace(go.Bar(
        x=list(loads.keys()), y=list(loads.values()),
        marker_color=['#FF4B4B', '#FACC15', '#4B4B4B'],
        text=list(loads.values()), textposition='auto',
    ), row=2, col=1)

    fig.update_layout(
        title_text="🏥 ST. JUDE'S | BIOMEDICAL INFRASTRUCTURE COMMAND",
        template="plotly_dark",
        height=700,
        paper_bgcolor="black",
        plot_bgcolor="black",
        font=dict(family="Courier New, monospace", color="white")
    )

    fig.show()

render_modern_hospital_dash()