# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6LxIIugsjFpBFTpaOgRKY_o1CfBs3OC
"""

import sqlite3
import pandas as pd

# 1. Connect to a database file (Colab will create this in the 'Files' tab on the left)
conn = sqlite3.connect('logistics_tower.db')
cursor = conn.cursor()

# 2. Create your Master Shipment Table
cursor.execute('''
CREATE TABLE IF NOT EXISTS GlobalShipments (
    ShipmentID INTEGER PRIMARY KEY,
    ShipName TEXT,
    OriginPort TEXT,
    DestinationPort TEXT,
    ScheduledArrival DATE,
    CurrentLat REAL,
    CurrentLon REAL,
    RiskLevel TEXT DEFAULT 'Low'
)
''')

# 3. Add a real ship to track
cursor.execute('''
INSERT INTO GlobalShipments (ShipName, OriginPort, DestinationPort, ScheduledArrival, CurrentLat, CurrentLon)
VALUES ('Maersk Advancer', 'Shanghai', 'Lagos', '2026-05-20', 31.23, 121.47)
''')

conn.commit()
print("Database 'logistics_tower.db' is LIVE in the cloud.")

# 4. View your data to make sure it's there
df = pd.read_sql_query("SELECT * FROM GlobalShipments", conn)
conn.close()
df

import sqlite3
from datetime import datetime

def update_shipment_status(shipment_id, new_lat, new_lon):
    conn = sqlite3.connect('logistics_tower.db')
    cursor = conn.cursor()

    # 1. Fetch the OLD position to compare
    cursor.execute("SELECT CurrentLat, CurrentLon FROM GlobalShipments WHERE ShipmentID = ?", (shipment_id,))
    old_data = cursor.fetchone()
    old_lat, old_lon = old_data[0], old_data[1]

    # 2. THE LOGIC: If position is EXACTLY the same, it's a potential delay
    if new_lat == old_lat and new_lon == old_lon:
        risk = "HIGH - Vessel Stationary"
        print(f"⚠️ ALERT: Shipment {shipment_id} has not moved. Risk set to HIGH.")
    else:
        risk = "Low"
        print(f"✅ Shipment {shipment_id} is on the move. Risk set to Low.")

    # 3. Update the database with the new info and the new Risk Level
    cursor.execute('''
        UPDATE GlobalShipments
        SET CurrentLat = ?, CurrentLon = ?, RiskLevel = ?
        WHERE ShipmentID = ?
    ''', (new_lat, new_lon, risk, shipment_id))

    conn.commit()
    conn.close()

# --- TEST THE SYSTEM ---
# Let's simulate a ping where the ship stayed at the same coordinates (31.23, 121.47)
update_shipment_status(1, 32.23, 122.47)

def generate_ai_report(shipment_id):
    conn = sqlite3.connect('logistics_tower.db')
    cursor = conn.cursor()

    # Get the latest data for the ship
    cursor.execute("SELECT * FROM GlobalShipments WHERE ShipmentID = ?", (shipment_id,))
    data = cursor.fetchone()
    conn.close()

    ship_name, origin, dest, arrival, lat, lon, risk = data[1], data[2], data[3], data[4], data[5], data[6], data[7]

    print(f"--- AI EXECUTIVE SUMMARY FOR {ship_name.upper()} ---")

    if "HIGH" in risk:
        report = f"""
        STATUS ALERT: CRITICAL DELAY DETECTED
        -------------------------------------
        The vessel is currently stationary at Lat {lat}, Lon {lon}.
        Projected impact on Destination ({dest}): Potential 48-72 hour slippage.

        PRESCRIPTIVE ACTION:
        1. Contact Port Authority at {origin} for congestion updates.
        2. Notify inland logistics providers in Lagos of a delayed berthing window.
        3. Check weather patterns in the current sector for storm-related stasis.
        """
    else:
        report = f"""
        STATUS: NOMINAL
        -------------------------------------
        The vessel is proceeding on schedule.
        Current ETA to {dest} remains {arrival}.
        No intervention required.
        """

    print(report)

# --- EXECUTE REPORT ---
generate_ai_report(1)

import requests

def get_live_ship_data(imo_number):
    # This is a 'Mock' API call. In a real scenario, you'd use a real URL + API Key.
    # For now, we are structuring the code so it's 'Plug-and-Play' for a real API.

    api_url = "https://api.searates.com/v1/vessel_tracking" # Example URL
    api_key = "YOUR_TRIAL_KEY_HERE"

    # Let's simulate what the API sends back to your Python script:
    mock_api_response = {
        "vessel_name": "Maersk Advancer",
        "last_lat": 6.45,  # Near Lagos!
        "last_lon": 3.39,
        "status": "Underway using Engine",
        "eta": "2026-05-10"
    }

    print(f"📡 API PING: Successfully retrieved live data for IMO {imo_number}")
    return mock_api_response

# --- THE INTEGRATION ---
# 1. Get real-world data
live_data = get_live_ship_data(9400071) # Example IMO for a real Maersk ship

# 2. Feed it into your System's Brain (from Step 2)
# This connects the 'Internet' to your 'SQL Database'
update_shipment_status(1, live_data['last_lat'], live_data['last_lon'])

import plotly.graph_objects as go
import sqlite3

def visualize_shipment(shipment_id):
    # 1. Connect to our 'Brain' (The Database)
    conn = sqlite3.connect('logistics_tower.db')
    cursor = conn.cursor()
    cursor.execute("SELECT ShipName, CurrentLat, CurrentLon, OriginPort, DestinationPort, RiskLevel FROM GlobalShipments WHERE ShipmentID = ?", (shipment_id,))
    data = cursor.fetchone()
    conn.close()

    ship_name, lat, lon, origin, dest, risk = data

    # 2. Create the Map
    fig = go.Figure(go.Scattergeo(
        lat = [lat],
        lon = [lon],
        mode = 'markers+text',
        text = [f"{ship_name} ({risk})"],
        textposition = "top center",
        marker = dict(
            size = 12,
            color = 'red' if 'HIGH' in risk else 'green',
            symbol = 'boat',
            line = dict(width=2, color='white')
        )
    ))

    # 3. Style the Map to look like a 'Control Tower'
    fig.update_layout(
        title = f'Real-Time Tracking: {ship_name} (Route: {origin} to {dest})',
        geo = dict(
            projection_type = 'equirectangular',
            showland = True,
            landcolor = "rgb(212, 212, 212)",
            countrycolor = "rgb(255, 255, 255)",
            showocean = True,
            oceancolor = "rgb(10, 25, 50)" # Deep navy for a professional look
        ),
        margin={"r":0,"t":40,"l":0,"b":0}
    )

    fig.show()

# --- SHOW THE MAP ---
visualize_shipment(1)

import plotly.graph_objects as go
import sqlite3

def visualize_shipment(shipment_id):
    try:
        # 1. Connect and Fetch
        conn = sqlite3.connect('logistics_tower.db')
        cursor = conn.cursor()
        cursor.execute("SELECT ShipName, CurrentLat, CurrentLon, OriginPort, DestinationPort, RiskLevel FROM GlobalShipments WHERE ShipmentID = ?", (shipment_id,))
        data = cursor.fetchone()
        conn.close()

        if data is None:
            print(f"❌ Error: No shipment found with ID {shipment_id}")
            return

        ship_name, lat, lon, origin, dest, risk = data

        # Debug Print: This helps us see if the data is correct
        print(f"Drawing map for {ship_name} at coordinates: ({lat}, {lon})")

        # 2. Create the Map
        fig = go.Figure(go.Scattergeo(
            lat = [lat],
            lon = [lon],
            mode = 'markers+text',
            text = [f"{ship_name}"],
            textposition = "top center",
            marker = dict(
                size = 15,
                color = 'red' if 'HIGH' in risk else 'green',
                symbol = 'diamond', # Using diamond as it's more stable in some Plotly versions
                line = dict(width=2, color='white')
            )
        ))

        # 3. Layout Settings
        fig.update_layout(
            title = f'Real-Time Tracking: {ship_name} ({risk})',
            geo = dict(
                scope = 'world',
                showland = True,
                landcolor = "rgb(243, 243, 243)",
                countrycolor = "rgb(204, 204, 204)"
            )
        )

        fig.show()

    except Exception as e:
        print(f"❌ An error occurred: {e}")

# --- EXECUTE ---
visualize_shipment(1)

import sqlite3
import pandas as pd

def upgrade_to_fleet_system():
    conn = sqlite3.connect('logistics_tower.db')
    cursor = conn.cursor()

    # 1. Add a 'Weather' column to our database
    try:
        cursor.execute("ALTER TABLE GlobalShipments ADD COLUMN LocalWeather TEXT")
        cursor.execute("ALTER TABLE GlobalShipments ADD COLUMN LastWindSpeed REAL")
    except sqlite3.OperationalError:
        pass # Column already exists

    # 2. Add two more ships to create a 'Fleet'
    # One is in the Atlantic, one is near the Suez Canal
    ships = [
        ('CMA CGM Liberty', 'Marseille', 'Lagos', '2026-05-25', 12.50, -15.20, 'Clear'),
        ('Ever Given II', 'Singapore', 'Rotterdam', '2026-06-01', 29.97, 32.53, 'High Winds')
    ]

    cursor.executemany('''
        INSERT INTO GlobalShipments (ShipName, OriginPort, DestinationPort, ScheduledArrival, CurrentLat, CurrentLon, LocalWeather)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', ships)

    conn.commit()
    conn.close()
    print("🚀 System Upgraded: Fleet Monitoring and Weather Tracking Enabled.")

upgrade_to_fleet_system()

def fleet_audit():
    conn = sqlite3.connect('logistics_tower.db')
    # Use Pandas to read the whole fleet at once
    df = pd.read_sql_query("SELECT * FROM GlobalShipments", conn)

    def calculate_risk(row):
        # Professional Logic: Context-Aware Risk
        if row['LocalWeather'] == 'High Winds' and row['RiskLevel'] == 'High':
            return "MODERATE (Weather Delay)"
        elif row['LocalWeather'] == 'Clear' and row['RiskLevel'] == 'High':
            return "CRITICAL (Unknown Stasis)"
        return row['RiskLevel']

    df['RefinedRisk'] = df.apply(calculate_risk, axis=1)
    conn.close()

    return df[['ShipName', 'DestinationPort', 'LocalWeather', 'RefinedRisk']]

# Execute the Audit
fleet_summary = fleet_audit()
fleet_summary